service: ch-appraisal-api
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000    

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  httpApi:
    cors: true  

#  environment:
#    variable1: value1

functions:
  hello:
    handler: handler.communeAll
    events:
      - httpApi:
          path: /commune/all
          method: get
